"""empty message

Revision ID: 317337905111
Revises: 
Create Date: 2024-02-04 11:06:41.349883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "317337905111"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_cost", sa.Numeric(), nullable=False),
        sa.CheckConstraint(
            "total_cost > 0", name="subscription_total_cost_check"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("notification_time", sa.Time(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_subscription",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Numeric(), nullable=False),
        sa.Column("send", sa.Boolean(), nullable=False),
        sa.Column(
            "debt", sa.Numeric(), server_default=sa.text("0"), nullable=False
        ),
        sa.CheckConstraint("cost > 0", name="user_subscription_cost_check"),
        sa.CheckConstraint("debt >= 0", name="user_subscription_debt_check"),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "subscription_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_subscription")
    op.drop_table("users")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
